Implement deploy script for contracts stack
nation3/court pull request #30
Opened 2022-08-09 22:12 UTC by xPi2

Task details: https://app.dework.xyz/nation3/nation3-court-v1-p?taskId=85c1f9c7-95f9-4eb5-878f-0f0db169b3fb

2022-08-10 12:47 UTC, aahna-ashina requested changes
@xPi2 This PR has 16 commits, but I think only one of these commits is the actual "Implement deploy script for contracts stack"?  Where are the other changes coming from?

2022-08-10 17:56 UTC, xPi2 commented
Sorry @aahna-ashina I created the draft before the merge of the collateral agreement branch from this branch forked, so it included all the changes from that branch also. Now is more clear what it's included in the PR

2022-08-15 17:16 UTC, gregfromstl approved these changes

2022-08-15 17:19 UTC, merged

2022-08-17 02:07 UTC, aahna-ashina reviewed
👍

2022-08-17 02:07 UTC, aahna-ashina commented on README.md
> +Start Anvil node:
@xPi2 Include a link to Anvil installation instructions.

2022-08-17 02:07 UTC, aahna-ashina commented on script/CollateralAgreementDeployer.s.sol
> +// SPDX-License-Identifier: UNLICENSED
`GPL-3.0-or-later`