chore: upgrade to solidity 0.8.14
nation3/court pull request #34
Opened 2022-08-17 02:34 UTC by aahna-ashina

https://app.dework.xyz/nation3/develop-1?taskId=5c7b4f2b-b72b-46d5-818d-a5d2d10fcda2

close #33

2022-08-17 08:55 UTC, xPi2 requested changes
Based on the releases documentation I recommend not updating to 0.8.14. If we want to update we should do it to 0.8.15 that at least includes the `.selector` for errors and events (very usefull for tests) and doesn't have the problem with the npm package

2022-08-17 08:57 UTC, xPi2 commented
Being "up to date" with solidity releases is not allways a good thing 😅

2022-08-18 02:26 UTC, aahna-ashina commented
> If we want to update we should do it to 0.8.15

@xPi2 Done:  https://github.com/nation3/court/pull/34/commits/368f0b1bdf3562d3588af2594b3d2a745b77db08

2022-08-18 09:43 UTC, xPi2 approved these changes

2022-08-18 09:43 UTC, merged