Create UI Project
nation3/court pull request #39
Opened 2022-08-21 18:29 UTC by gregfromstl

Dework task: https://app.dework.xyz/nation3/court?taskId=f419a62c-7ed2-4100-baac-8c4cd8ab9dc8

2022-08-22 11:46 UTC, xPi2 approved these changes

2022-08-22 13:11 UTC, luisivan requested changes
Pretty sure you're not supposed to commit `.next`?

2022-08-23 05:30 UTC, gregfromstl commented
> Pretty sure you're not supposed to commit `.next`?

Good catch. Fixed 🔨

2022-08-23 06:53 UTC, luisivan approved these changes
✨

2022-08-30 02:40 UTC, merged